language: node_js
node_js:
  - "node"
  - "7"
  - "6"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
services:
  - postgresql
install:
  - ./misc/travis-install.sh
script:
  - ./misc/travis-script.sh
