#%RAML 1.0 DataType
type: object
properties:

  body:
    type: string
    minLength: 1
    maxLength: 10000
    required: true

  visibility:
    type: !include publicOrPrivate.raml
    | !include shared.raml
    required: true
